### ISSUE TITLE
info for "/local/marked.min.js?v=4.2.12"

### ISSUE THREAD

**Issue by barto95100** [troinine/hass-config#4]
Hi, I test your dashboard it's beautiful..

just a question what is this ? because on your folder in github the marked.js not appear ? 

how can i do because I have the error on button-card template 

thank's for your response :)

**Comment by troinine** [comment]
Hi and thanks for the feedback!

MarkedJS is one of the dependencies that is not managed at this point. You can download the respective version from https://cdn.jsdelivr.net/npm/marked@4.2.12/ and place it under the `www` folder which should make it available.

Hope this helps!

**Comment by troinine** [comment]
Hi and thanks for the feedback!

MarkedJS is one of the dependencies that is not managed at this point. You can download the respective version from https://cdn.jsdelivr.net/npm/marked@4.2.12/ and place it under the `www` folder which should make it available.

Hope this helps!
