### ISSUE TITLE
Error loading /config/configuration.yaml: Secret todoist_home_project_id not defined

### ISSUE THREAD

**Issue by stromen1** [troinine/hass-config#5]
Hi,

can you help me? 

I got this error: Error loading /config/configuration.yaml: Secret todoist_home_project_id not defined

Thanks.

**Comment by RubenDijk** [comment]
it looks like your secrets are not loading or are not properly referenced. 
https://www.home-assistant.io/docs/configuration/secrets#using-secretsyaml

**Comment by stromen1** [comment]
Thanks, I was able to solve the problem, but I still have another one. I'm trying to get the weather integration to work but I'm having trouble. Which is this and where exactly is it configured „weather.koti“?

**Comment by RubenDijk** [comment]
> Thanks, I was able to solve the problem, but I still have another one. I'm trying to get the weather integration to work but I'm having trouble. Which is this and where exactly is it configured „weather.koti“?

sorry for my late response. i think then you are looking for the following location: https://github.com/troinine/hass-config/blob/main/popups/common/weather-forecast.yaml

then line number 33

**Comment by troinine** [comment]
Hey @stromen1! And thanks to @RubenDijk for providing support here! Few bits to add.

`weather.koti` is my personal weather entity. Your HA has probably your own with a different name, assuming you have enabled a weather integration. I personally use [AccuWeather](https://www.home-assistant.io/integrations/accuweather/).

When you have enabled a weather integration you can see a `weather` sensor. `weather.koti` is used in few places but a find-and-replace with VSCode for example will do the trick for you 😄.
